spring.application.name=CSRKSpringApplication

#Oracle Database configuration
spring.datasource.url=jdbc:oracle:thin:@//3.90.4.196:1521/XEPDB1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=HR
spring.datasource.password=Test1ng1
spring.datasource.initialization-mode=always
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.read-only=false
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.csrk.userinfo=DEBUG
logging.file.name=logs/application.log

# AWS Cognito configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XC2OfL9rK
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XC2OfL9rK/.well-known/jwks.json
spring.security.oauth2.client.registration.cognito.client-id=urum8lp96psjletummjiqi3nc
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:8080/login/oauth2/code/cognito
spring.security.oauth2.client.registration.cognito.client-secret=101ab10rubchh7gn84854meamon2cus5e88bue304ops0o4ong7j
spring.security.oauth2.client.provider.cognito.authorization-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XC2OfL9rK/oauth2/authorize
spring.security.oauth2.client.provider.cognito.token-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XC2OfL9rK/oauth2/token
spring.security.oauth2.client.provider.cognito.user-info-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XC2OfL9rK/userinfo